### ISSUE TITLE
Frontend Update

### ISSUE THREAD

**Issue by brandoncroberts** [awslabs/aws-media-replay-engine#29]
Hello,
I'm interested in this project, as I have ambitions to work at the intersection of Technology / Sports.
I have experience with AWS and also have frontend expertise.
I noticed the frontend part of the app has quite a lot of tech debt. 
- Dependencies several years out of date, eg.  React
- General code quality issues, ie. many unused variables / imports

Therefore I'm wondering if you'd be interested in my contributions to the frontend part of the repository.
Thanks and have a nice day!

**Comment by aravindgilead** [comment]
Hi Brandon, thanks for reaching out. With the new MRE v2.9.0 release, we've upgraded both Frontend and Backend dependent packages/libs to latest versions. I would encourage you to use the new MRE version. We'd be interested to know your ideas for improving the frontend experience. Would you mind sharing these?

**Comment by brandoncroberts** [comment]
> Hi Brandon, thanks for reaching out. With the new MRE v2.9.0 release, we've upgraded both Frontend and Backend dependent packages/libs to latest versions. I would encourage you to use the new MRE version. We'd be interested to know your ideas for improving the frontend experience. Would you mind sharing these? 
> 

The timing is interesting of the release! I didn't release you had some branch in progress with upgrades to the Frontend also!
I'll take a look at the code more when I have some time, but for now I see that you updated some key packages such as React. 
One potential idea could be migrate the Frontend to one of the current recommended React frameworks, such as Next.js or Remix

**Comment by brandoncroberts** [comment]
I will close this, since it looks like you recently merged something along the lines of my suggestion! :)
