### ISSUE TITLE
Unable to locate credentials. You can configure credentials by running "aws configure"

### ISSUE THREAD

**Issue by Laazarus** [awslabs/aws-media-replay-engine#43]
Hello, I keep receiving this error when I execute the script 

sudo ./build-and-deploy.sh --disable-ui --version $VERSION --region $REGION

aws-cdk  is correctly installed (Ubuntu Linux) and aws-cli is configured already (I did run the command aws configure and inserted the secret and access keys).

The only thing I can see is that if I run aws --version  I get this result:

aws --version
aws-cli/2.18.0 Python/3.12.6 Linux/5.15.153.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.24

The standard version of Python for my ubuntu was 3.12 U had to install the version 3.11 but the aws cli keeps showing python 3.12

Thanks for the help

**Comment by Laazarus** [comment]
After some investigation I found that the problem is given by the fact that the script does not find the cdk command

`# # Check if cdk is installed
if [[ ! -x "$(command -v cdk)" ]]; then
  echo "ERROR: Command not found: cdk"
  echo "ERROR: This script requires the AWS CDK to be installed"
  echo "ERROR: Please install it and rerun this script. Refer: https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_install"
  exit 1
fi`

This check always fails even if the cdk is correctly configured and installed in the system. 

Anyone else had this problem? 

node version 22.9.0 lts
running in the terminal this command 
` command -v cdk`
displays the following:
`/home/nicola/.nvm/versions/node/v22.9.0/bin/cdk`

Thanks for the help :)

**Comment by araviraj-aws** [comment]
Hi @Laazarus ! Can you please try running the deployment script (build-and-deploy.sh) without `sudo` and see if that makes the script pick up the AWS credentials? Thanks!

**Comment by Laazarus** [comment]
Hello, Yes I am trying it now, it is failing when trying to delete some files because they where created under sudo. I am re-cloning the repo from scratch and trying to run without sudo.

**Comment by Laazarus** [comment]
Hello,

Yes Now the script can find the credentials and can progress but it fails giving an error like 

`[Error at /aws-mre-shared-resources/mre-media-output/Resource] AwsSolutions-CFR7: The CloudFront distribution does not use an origin access control with an S3 origin. Origin access controls help with security by restricting any direct access to objects through S3 URLs.`

**Comment by Laazarus** [comment]
Hi @araviraj-aws,

I just did what you said and everything went smoothly and the deployment was completed successfully.

Thanks so much for your help and support in this, you are brilliant :)
